### ISSUE TITLE
How to hide the background view?

### ISSUE THREAD

**Issue by Nandulucky** [gabemdev/GMDCircleLoader#2]
Hi, I'm using GMDCirlceLoader.
It looks great. But i want to hide the background view.
For Ex: I'm working on login page with using GMDCircleLoader, it shows loading spinner but when I'm click the username textField the keyboard is open.
I want to hide the background screen when I'm using GMDCircleLoader.
Please help me ASAP.

Thanks in Advance.

**Comment by gabemdev** [comment]
Hi @Nandulucky, i'm not sure if I understand your question. Are you loading the hud before you load your username/password view? 

To hide GMDCircleLoader you can refer to : 
https://github.com/gabemdev/GMDCircleLoader#dismissing-the-loading-view

There is also an example in the documentation: 
```
- (void)loginTwitter:(id)sender {
[GMDCircleLoader setOnView:self.view withTitle:@"Loading..." animated:YES];
[[Twitter sharedInstance] loginWithCompletion:^(TWTRSession *session, NSError *error) {
    if (session) {
        [GMDCircleLoading hideHUDFromView:self.view animated:YES];
                }
}
```

**Comment by gabemdev** [comment]
Closing as no response from above.
