### ISSUE TITLE
How to give frame for loader?

### ISSUE THREAD

**Issue by chinnuios** [gabemdev/GMDCircleLoader#3]
Hi, is there any possibility to give frame for the loader. Becoz I want it on landscape mode but it not showing center of view. Thanks in advance.

**Comment by gabemdev** [comment]
Hi, sure you can update the frame of the loader, spinner and image. 

In GMDCircleLoader.h
```
#define GMD_SPINNER_FRAME       CGRectMake(40.0f, 40.0f, 40.0f, 40.0f)
#define GMD_SPINNER_IMAGE       CGRectMake(15, 15,30,30)
```

In GMDCircleLoader.m
Look at the `setOnView` class method. 
```
    float height = [[UIScreen mainScreen] bounds].size.height;
    float width = [[UIScreen mainScreen] bounds].size.width;
    CGPoint center = CGPointMake(width/2, height/2);
    hud.center = center;
    return hud;
```
